server:
  port: 8081
  address: 0.0.0.0
logging:
  config: classpath:logback-spring.xml
datasource:
  api: http://localhost:8080/v1/enginer-data
enginer:
  scanner:
    base-packages: br.com.enginer.domain
spring:
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB
management: # http://localhost:8081/actuator
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,beans,mappings,metrics,startup
  endpoint:
    startup:
      enabled: true 